[package]
name = "deckompiler"
description = "Tool for Tickompiler formats"
version = "0.2.0-dev"
edition = "2021"
default-run = "deckompiler"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytestream = "0.4"
clap = {version = "3.2", features=["derive"]}

[[bin]]
name = "c00"