[package]
name = "deckompiler"
description = "Tool for Tickompiler formats"
version = "0.1.0"
edition = "2021"
default-run = "deckompiler"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytestream = "0.4.1"
ips = "0.1.0"
clap = {version = "3.1", features=["derive"]}

[[bin]]
name = "c00"